services:
  # --- Votre Service Applicatif ---
  auth-service:
    container_name: auth-service
    build:
      context: . # Le contexte est à la racine du monorepo
      dockerfile: auth-service/Dockerfile # On spécifie le chemin vers le Dockerfile
    ports:
      - "3000:3000"
    environment:
      # L'URL de connexion pointe vers le service postgres-db
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB_AUTH}?schema=public"
      FRONTEND_URL: "http://localhost:5173"
      ACCESS_TOKEN_SECRET: "8F67FECA883AAB7585DA7784A2745"
      REFRESH_TOKEN_SECRET: "521DE98CAEEC14C869992DA637685"
      ACCESS_TOKEN_EXPIRATION: "15m"
      REFRESH_TOKEN_EXPIRATION: "7d"
    depends_on:
      - postgres-db
    networks:
      - godet-net
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"

  # --- Base de Données ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
    ports:
      - "5433:5432" # Permet de se connecter à la BDD depuis votre machine locale si besoin
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistance des données de la BDD
    networks:
      - godet-net

  # --- Stack de Monitoring ELK ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Simplicité pour le développement local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limite la mémoire utilisée par Elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data # Persistance des données d'Elasticsearch
    networks:
      - godet-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601" # Port de l'interface web de Kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Dit à Kibana où trouver Elasticsearch
    networks:
      - godet-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    ports:
      - "12201:12201/udp" # On expose le port GELF
    volumes:
      # On monte notre fichier de configuration
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - godet-net

# --- Volumes Nommés (pour la persistance des données) ---
volumes:
  postgres-data:
  elasticsearch-data:

# --- Réseau Personnalisé (pour que les services se trouvent par leur nom) ---
networks:
  godet-net:
    driver: bridge