# filebeat.yml
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            # CONDITION TRÈS STRICTE :
            # On ne s'intéresse qu'au conteneur dont le nom est EXACTEMENT "auth-service"
            equals:
              docker.container.name: "auth-service"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              
              # On dit à Filebeat que TOUT ce qu'il lit de ce conteneur est du JSON
              json.keys_under_root: true
              json.add_error_key: true
              json.message_key: msg

# On remet la sortie vers Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]